<?php

return [
    'frontend_sections' => [
        'Accessories',
        'Automotive',
        'Baby & Kids',
        'Baby Products',
        'Bags',
        'Bags & Travel',
        'Beauty',
        'Books & Magazines',
        'Books & Stationery',
        'Clothing',
        'Cosmetics',
        'Cosmetics & Beauty',
        'Digital Products',
        'Dining',
        'Electrical Products',
        'Electronics',
        'Fashion',
        'Fashion & Clothing',
        'Fitness',
        'Food',
        'Food & Grocery',
        'Footwear',
        'Furniture',
        'Gadgets & Accessories',
        'Grocery',
        'Grocery & Food',
        'Health',
        'Health & Personal Care',
        'Home',
        'Home & Furniture',
        'Home Decor',
        'Hot Deals',
        'Innerwear',
        'Jewelry',
        'Jewelry & Accessories',
        'Kitchen',
        'Kitchen & Dining',
        'Panjabi',
        'Personal Care',
        'Pet Products',
        'Service',
        'Service Categories',
        'Shirt',
        'Shoes',
        'Shoes & Footwear',
        'Sports',
        'Sports & Fitness',
        'T-Shirt',
        'Test Category',
        "Toy's",
        'Toys',
        'Toys & Baby Products',
        'Travel',
        "Women's Shopping",
        'কাপড় ড্রেস',
        'কুর্তি ও গাউন',
        'ঘড়ি',
        'চশমা',
        'জুতা',
        'টুপি',
        'থ্রি-পিস',
        'পাঞ্জাবী',
        'প্যান্ট',
        'ফার্নিচার',
        'বাচ্চাদের জামা',
        'বুটিকস থ্রিপিস',
        'বেডশীট',
        'বোরকা',
    ]
];
